name: flutter_ml
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.0
  provider: ^6.0.0
  image_picker: ^0.8.4+3
  http: ^0.13.3
  percent_indicator: ^3.4.0
  step_progress_indicator: ^1.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.2"

flutter:
  uses-material-design: true



